[package]
name = "vyn"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5", features = ["derive"] }
colored = "3.0.0"
indicatif = "0.18.3"
num_enum = "0.7.5"
terminal_size = "0.4.3"
